name: Interface CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install and configure
        run: |
          npm run build
